# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lr_scheduler <- function(n_itr = 3000L, lr0 = 0.1, gamma = 0.8, decay_period = 50L, cyclic_period = 200L) {
    .Call(`_sgdpd_lr_scheduler`, n_itr, lr0, gamma, decay_period, cyclic_period)
}

sigmoid <- function(z) {
    .Call(`_sgdpd_sigmoid`, z)
}

apply_f <- function(f, Z, theta) {
    .Call(`_sgdpd_apply_f`, f, Z, theta)
}

sgdpd <- function(f, Z, theta0, lr, positives = 0L, conditions = 0L, exponent = 0.1, N = 20L, M = 2L, showProgress = TRUE, h = 10^(-10), log_interval = 10L) {
    .Call(`_sgdpd_sgdpd`, f, Z, theta0, lr, positives, conditions, exponent, N, M, showProgress, h, log_interval)
}

